name: Build and Deploy Blazor WASM to Cloudflare Pages

on:
  push:
    branches:
      - main  # Triggers on push to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Or change to 7.0.x if needed

      - name: Publish Blazor WASM
        run: dotnet publish -c Release -o publish

      - name: Deploy wwwroot to deploy branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: deploy
          folder: publish/wwwroot
